[project]
name = "mcp"
version = "0.1.0"
description = "MCP client and server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "openai-agents>=0.0.7",
    "uvicorn>=0.34.2",
]
